# This workflow builds and tests async-websocket 
# on events:
#   - pushes
#   - pull-requests
#
# on platforms:
#   - macOS 15
#   - latest Ubuntu
#
# interval:
#   - Once a day

name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
  schedule:
    - cron: 0 0 * * *

jobs:
  macOS-15:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  Ubuntu-latest:
    strategy:
      matrix:
        swift:
          - '6.0.2'
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
